### ISSUE TITLE
flam50. Why?

### ISSUE THREAD

**Issue by dschwilk** [XiulinGao/shade-flammability#15]
Why does this data frame exist?  I found its origin in analyses.R line 32

But why?  It adds to duplicated code throughout `fig-tables.R`. I see no reason for its existence. It is a subset of flamdt and it appears that it was created solely to avoid putting NAs into flamdt. But what is the cost of those NAs?  I don't understand the problem.

**Comment by XiulinGao** [comment]
yes, it is the subset of flamdt just to drop obs for heat50 from the first trial. no, there is no cost of just introducing NAs into flamdt. The only reason I did this is this is the most straightforward way for me to drop obs for heat50 really. Go ahead to improve it in your way.

**Comment by dschwilk** [comment]
Ok, good I thought I was missing something.  I'll eliminate that. Then combining figs 2 and 3 will be easier.

**Comment by XiulinGao** [comment]
solved with 9b2b02824dbbfebd9536fea4eff637c318d166b7
