### ISSUE TITLE
Back transform y-axis (in log) for figures

### ISSUE THREAD

**Issue by XiulinGao** [XiulinGao/shade-flammability#9]
I need to back transform the y-axis that is log-transformed in manuscript figures. 
script is located at ../scripts/fig-table.R @dschwilk

**Comment by XiulinGao** [comment]
Added code to change the tick marks in format of e^ to show the actual number. 8b4918a7313df870a65a05bff8f1996fb1be8f0a
but still need to check if this is the right way to do

**Comment by dschwilk** [comment]
These should be log10 and no need for exponential notation, just have nice even values for breaks.

**Comment by XiulinGao** [comment]
Sure. I can change to log10

**Comment by XiulinGao** [comment]
solved with 0e193f40467dfeaf7aa663b93b7de8c5553a6038
